### ISSUE TITLE
不明白你的IMvpView 主要功能是什么？

### ISSUE THREAD

**Issue by csi0n** [LiushuiXiaoxia/XiaoxiaZhihu#10]
不明白你的IMvpView 主要功能是什么，没看到使用的方法，能不能举个例子看下？谢谢！

**Comment by LiushuiXiaoxia** [comment]
仅仅只是做一个标示而已，比如java中的java.lang.Cloneable

java里面有这种用法的。

所有集成的子类都是一个mvpview接口
